In [3]:
import numpy as np

# Axis

`axis=0` sums columns

`axis=1` sums rows

In [17]:
x = np.array([[1,2,3],
              [30,40, 50]])

display(np.sum(x,axis=0)) #sum columns
display(np.array([np.sum(x[:,i]) for i in range(x.shape[1])]))
display(np.sum(x,axis=1)) #sum rows
display(np.array([np.sum(x[i,:]) for i in range(x.shape[0])]))


array([31, 42, 53])

array([31, 42, 53])

array([  6, 120])

array([  6, 120])

In [9]:
x.shape

(2, 2)

# 3D arrays

In [19]:
A = np.array([[[1,20],[3,4]],[[5,9],[70,8]],[[9,10],[11,12]]])
i = np.array(['a','b'])
A

array([[[ 1, 20],
        [ 3,  4]],

       [[ 5,  9],
        [70,  8]],

       [[ 9, 10],
        [11, 12]]])

In [32]:
display(np.sum(A))
display(np.sum(A,axis=0))
display(np.sum(A,axis=0, keepdims=True))
display(np.sum(A,axis=1))
display(np.sum(A,axis=1, keepdims=True))
display(np.sum(A,axis=2))
display(np.sum(A,axis=2, keepdims=True))
display(np.sum(A, axis=(0,1)))
display(np.sum(A, axis=(0,1),keepdims=True))
display(np.sum(A, axis=(0,2)))
display(np.sum(A, axis=(0,2),keepdims=True))
display(np.sum(A, axis=(1,2)))
display(np.sum(A, axis=(1,2),keepdims=True))

162

array([[15, 39],
       [84, 24]])

array([[[15, 39],
        [84, 24]]])

array([[ 4, 24],
       [75, 17],
       [20, 22]])

array([[[ 4, 24]],

       [[75, 17]],

       [[20, 22]]])

array([[21,  7],
       [14, 78],
       [19, 23]])

array([[[21],
        [ 7]],

       [[14],
        [78]],

       [[19],
        [23]]])

array([99, 63])

array([[[99, 63]]])

array([ 54, 108])

array([[[ 54],
        [108]]])

array([28, 92, 42])

array([[[28]],

       [[92]],

       [[42]]])

In [229]:
#Take the max of each column.
#display(np.max(A,axis=1))
#Find the argmax
#display(np.argmax(A,axis=1))
i_max = i[np.argmax(A,axis=1)]
print(i_max)

np.repeat(i_max,2).reshape(3,2,2).transpose(0,2,1)

[['b' 'a']
 ['b' 'a']
 ['b' 'b']]


array([[['b', 'a'],
        ['b', 'a']],

       [['b', 'a'],
        ['b', 'a']],

       [['b', 'b'],
        ['b', 'b']]], dtype='<U1')

In [141]:
display(np.max(A))
display(np.max(A,axis=0)) #compare A[i,j,k] for given j,k
display(np.max(A,axis=1)) #compare A[i,j,k] for fixed i,k
display(np.max(A,axis=2)) #compare A[i,j,k] for fixed i,j
display(np.max(A,axis=(0,1))) #compare A[i,j,k] for fixed k
display(np.array([np.max(A[:,:,k]) for k in range(A.shape[2])]))
display(np.max(A,axis=(0,2)))
display(np.array([np.max(A[:,j,:]) for j in range(A.shape[1])]))
display(np.max(A,axis=(1,2))) #max of each inner array
display(np.array([np.max(A[i,:,:]) for i in range(A.shape[0])]))

70

array([[ 9, 20],
       [70, 12]])

array([[ 3, 20],
       [70,  8],
       [11, 12]])

array([[20,  4],
       [ 6, 70],
       [10, 12]])

array([70, 20])

array([70, 20])

array([20, 70])

array([20, 70])

array([20, 70, 12])

array([20, 70, 12])

In [209]:
np.array([np.unravel_index(np.argmax(iA),(2,2)) for iA in A])

array([[0, 1],
       [1, 0],
       [1, 1]], dtype=int64)

In [160]:
A

array([[[ 1, 20],
        [ 3,  4]],

       [[ 5,  6],
        [70,  8]],

       [[ 9, 10],
        [11, 12]]])

In [173]:
p=np.array([5,6])

In [174]:
A_star = np.repeat(np.max(A,axis=(1,2)),2*2).reshape(3,2,2)
A_star

array([[[20, 20],
        [20, 20]],

       [[70, 70],
        [70, 70]],

       [[12, 12],
        [12, 12]]])

In [175]:
A==A_star

array([[[False,  True],
        [False, False]],

       [[False, False],
        [ True, False]],

       [[False, False],
        [False,  True]]])

In [180]:
p_star=p[np.array([np.unravel_index(np.argmax(iA),(2,2)) for iA in A==A_star])[:,0]]

In [183]:
np.repeat(p_star,2*2).reshape(-1,2,2)

array([[[5, 5],
        [5, 5]],

       [[6, 6],
        [6, 6]],

       [[6, 6],
        [6, 6]]])

# Tile

In [ ]:
x=np.array([1,2,3])

display(np.tile(x,(2,1)))

x=np.array([[1,2],[3,4]])

display(np.tile(x,(1,2)))

$[a,b,c]\to \left[\begin{bmatrix}a&a\\a&a\end{bmatrix}\ ,\ \begin{bmatrix}b&b\\b&b\end{bmatrix}\ , \ \begin{bmatrix}c&c\\c&c\end{bmatrix}\right]$

In [80]:
np.repeat(x,4).reshape(len(x),2,2)

array([[[1, 1],
        [1, 1]],

       [[2, 2],
        [2, 2]],

       [[3, 3],
        [3, 3]]])

In [97]:
x=np.array([1,2,3])

np.tile(x,3).reshape(1,3,3)

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]])

In [10]:
np.array([1,10]).reshape(-1,1,1)*np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

array([[[ 1,  2],
        [ 3,  4]],

       [[50, 60],
        [70, 80]]])